/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChantSession {
  'count' : bigint,
  'timestamp' : bigint,
  'mantra' : string,
  'durationMillis' : [] | [bigint],
}
export interface DailyChantTotal {
  'date' : bigint,
  'count' : bigint,
  'mantra' : string,
}
export interface Mantra {
  'name' : string,
  'description' : string,
  'repetitions' : bigint,
}
export interface Streak {
  'lengthDays' : bigint,
  'endDate' : [] | [bigint],
  'isActive' : boolean,
  'startDate' : bigint,
}
export type SyncState = {};
export interface UserProfile {
  'displayName' : string,
  'selectedMantras' : Array<string>,
  'preferredSessionTimes' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChantSession' : ActorMethod<[ChantSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMantras' : ActorMethod<[], Array<Mantra>>,
  'getSessionSummaries' : ActorMethod<[], Array<ChantSession>>,
  'getStreaks' : ActorMethod<[], Array<Streak>>,
  'getSyncState' : ActorMethod<[], [] | [SyncState]>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'syncDailyChantTotals' : ActorMethod<[Array<DailyChantTotal>], undefined>,
  'updateSyncState' : ActorMethod<[SyncState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];