/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChantSession = IDL.Record({
  'count' : IDL.Nat,
  'timestamp' : IDL.Nat64,
  'mantra' : IDL.Text,
  'durationMillis' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'selectedMantras' : IDL.Vec(IDL.Text),
  'preferredSessionTimes' : IDL.Text,
});
export const Mantra = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'repetitions' : IDL.Nat,
});
export const Streak = IDL.Record({
  'lengthDays' : IDL.Nat,
  'endDate' : IDL.Opt(IDL.Nat64),
  'isActive' : IDL.Bool,
  'startDate' : IDL.Nat64,
});
export const SyncState = IDL.Record({});
export const DailyChantTotal = IDL.Record({
  'date' : IDL.Nat64,
  'count' : IDL.Nat,
  'mantra' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChantSession' : IDL.Func([ChantSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
  'getSessionSummaries' : IDL.Func([], [IDL.Vec(ChantSession)], ['query']),
  'getStreaks' : IDL.Func([], [IDL.Vec(Streak)], ['query']),
  'getSyncState' : IDL.Func([], [IDL.Opt(SyncState)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncDailyChantTotals' : IDL.Func([IDL.Vec(DailyChantTotal)], [], []),
  'updateSyncState' : IDL.Func([SyncState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChantSession = IDL.Record({
    'count' : IDL.Nat,
    'timestamp' : IDL.Nat64,
    'mantra' : IDL.Text,
    'durationMillis' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'selectedMantras' : IDL.Vec(IDL.Text),
    'preferredSessionTimes' : IDL.Text,
  });
  const Mantra = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'repetitions' : IDL.Nat,
  });
  const Streak = IDL.Record({
    'lengthDays' : IDL.Nat,
    'endDate' : IDL.Opt(IDL.Nat64),
    'isActive' : IDL.Bool,
    'startDate' : IDL.Nat64,
  });
  const SyncState = IDL.Record({});
  const DailyChantTotal = IDL.Record({
    'date' : IDL.Nat64,
    'count' : IDL.Nat,
    'mantra' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChantSession' : IDL.Func([ChantSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMantras' : IDL.Func([], [IDL.Vec(Mantra)], ['query']),
    'getSessionSummaries' : IDL.Func([], [IDL.Vec(ChantSession)], ['query']),
    'getStreaks' : IDL.Func([], [IDL.Vec(Streak)], ['query']),
    'getSyncState' : IDL.Func([], [IDL.Opt(SyncState)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncDailyChantTotals' : IDL.Func([IDL.Vec(DailyChantTotal)], [], []),
    'updateSyncState' : IDL.Func([SyncState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };